# this file is copyright free (public domain)

# this file is intended for use on a system running Gentoo Linux with `doas` for permissions

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.

if [[ $- != *i* ]] ; then
    return
fi

# Load aliases and shortcuts if existent
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/baliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/baliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/colors" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/colors"
