#!/bin/sh

# rosé pine colors for tty
if [ "$TERM" = "linux" ]; then
  /bin/echo -e "
  \e]P0403c58
  \e]P1ea6f91
  \e]P29bced7
  \e]P3f1ca93
  \e]P434738e
  \e]P5c3a5e6
  \e]P6eabbb9
  \e]P7faebd7
  \e]P86f6e85
  \e]P9ea6f91
  \e]PA9bced7
  \e]PBf1ca93
  \e]PC34738e
  \e]PDc3a5e6
  \e]PEeabbb9
  \e]PFffffff
  "
  clear
fi

# ANSI color escapes
GRA=$'\e[1;30m' # gray
RED=$'\e[1;31m' # red
GRN=$'\e[1;32m' # green
YEL=$'\e[1;33m' # yellow
BLU=$'\e[1;34m' # blue
MAG=$'\e[1;35m' # magenta
CYA=$'\e[1;36m' # cyan
WHI=$'\e[1;37m' # white

# ANSI text decorations
B=$'\e[1m' # bold
U=$'\e[4m' # underline
F=$'\e[5m' # flashing/blinking

# reset all text colors and decorations
RC=$'\e[0m'
