#!/bin/zsh

# add `~/.local/bin` and `~/.local/scripts` to $PATH
export PATH="$HOME/.local/bin:$HOME/.local/scripts:$PATH"

unsetopt PROMPT_SP

export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="st"
export BROWSER="librewolf-bin"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority" # This line will break some DMs
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# Other program settings:
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm

# Start graphical server on user's current tty if not already running.
# [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
