#!/bin/sh
url="https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$(urlencode "$*")" # 🦆

exec lynx "$url"
# exec w3m "$url"
# exec lynx "duckduckgo.com/lite?q=$*" # 🦆
# exec w3m "duckduckgo.com/lite?q=$*"
