#!/bin/sh

usage() {
    printf "%s\n" "usage: iic [server] [channel] [irc dir]"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

IRC_SERV=$1
shift

if [ $# -lt 1 ]; then
    usage
    printf "%s\n" "ERROR: no channel is provided"
    exit 1
fi

IRC_CHAN=$1
shift

if [ $# -lt 1 ]; then
    IRC_DIR=$HOME/irc
else
    IRC_DIR=$1
fi

clear
lchat -n 100 -t "#$IRC_CHAN" $IRC_DIR/$IRC_SERV/\#$IRC_CHAN
