#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged in, 🔋 for discharging battery, etc.).

case $BLOCK_BUTTON in
	1) nightlight ;;
	3) notify-send "Battery Module" "\- Left click to activate Night Light
- Scroll to adjust backlight
❗: battery very low!
🌙: night light enabled" ;;
	4) brillo -q -A 2 ;;
	5) brillo -q -U 2 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status" 2>&1)" in
		"Full") status="~" ;;
		"Discharging") status="<" ;;
		"Charging") status=">" ;;
		"Not charging") status="@" ;;
		"Unknown") status="? " ;;
		*) exit 1 ;;
	esac
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	[ "$status" = "<" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Show nightlight status
	colortemp="$(xsct | cut -d' ' -f5)"
	[ "$colortemp" -lt 6500 ] && night=" 🌙"
	# Prints the info
	printf "[ %s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "$night ]" "\\n"
