#!/bin/sh

case $BLOCK_BUTTON in
	3) notify-send "CPU temperature module " "Displays CPU temperature" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

temperature=$(sensors | awk '/Core 0/ {print $3}')

printf "%s" "[ $temperature |"
