#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s|..27m|</span></b>|")" && notify-send "Appointments" "$(calcurse -d3)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	3) notify-send "Time/date module" "\- Left click to show a full month view along with the next three days of upcoming appointments
- Middle click opens calcurse" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

status_clock=$(date "+%b %d (%a), %Y | %R %Z")

printf "%s" "[ $status_clock ]"
