#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🔒 if a vpn connection is active

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) notify-send "Internet module" "\- Left click to connect
❌: wifi disabled
: wifi connection with quality
" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	wifiicon="$(awk '/^\s*w/ { print "", int($3 * 100 / 70) "%" }' /proc/net/wireless)"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="? " || wifiicon="❌ "
fi

printf "[ %s%s \n" "$wifiicon" "$(sed "s/.*/🔒/" /sys/class/net/tun*/operstate 2>/dev/null)"
