#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) notify-send "Memory module" "Shows memory used/total
- Left click to show memory hogs" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

free --mebi | sed -n '2{p;q}' | awk '{printf (" %2.2fGiB/%2.2fGiB ]\n", ( $3 / 1024), ($2 / 1024))}'
