#!/bin/sh

# Prints the current volume

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
    3) notify-send "Volume module" "\- Left click to open pamixer
- Middle click to mute
- Scroll to change volume" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo "[ -  M ]" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -ge "100" ]; then
	icon=" "
elif [ "$vol" -ge "55" ]; then
	icon=" "
elif [ "$vol" -ge "10" ]; then
	icon=" "
elif [ "$vol" -gt "1" ]; then
	icon="  "
else
    echo "[ -  X ]" && exit
fi

echo "[ $icon$vol ]"
