#!/bin/sh

# Prints the current volume

case $BLOCK_BUTTON in
	1) pulsemixer --toggle-mute ;;
	2) setsid -f "$TERMINAL" -e pulsemixer ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
    3) notify-send "Volume module" "\- Scroll to change volume
- Left click to mute
- Middle click to open pulsemixer" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ "$(amixer -D pulse get Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $5 }')" = "off" ] && echo "[   ]" && exit

vol="$(amixer -D pulse get Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $3 }')"

icon=""

echo "[ $icon $vol ]"
