#!/bin/sh

# Mimeapp script for adding torrent to transmission-daemon, but will also start the daemon if not already running.

# transmission-daemon sometimes fails to take remote requests in its first moments, hence the sleep.

pidof transmission-daemon >/dev/null || (transmission-daemon && notify-send "Starting transmission-daemon..." && sleep 3 && pkil -RTMIN+7 "${STATUSBAR:-dwmblocks}")

transmission-remote -a "$@" && notify-send " Torrent added"
